# Generated by Django 5.0.3 on 2024-03-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('candidate', 'Candidate'), ('admin', 'Admin')], default='candidate', max_length=10, verbose_name='user type'),
        ),
    ]
