# Generated by Django 5.0.3 on 2024-03-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_course_qualificationtype_qualificationdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expriance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('numberofyears', models.IntegerField()),
            ],
        ),
    ]
