# Generated by Django 5.0.3 on 2024-03-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_expriance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expriance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateprofile'),
        ),
    ]
