# Generated by Django 5.0.3 on 2024-03-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_expriance_user'),
        ('employer', '0003_alter_companydata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appdyjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='job_applications')),
                ('cover_letter', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobdata')),
            ],
        ),
    ]
