# Generated by Django 5.0.3 on 2024-03-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_alter_candidateprofile_bio'),
        ('employer', '0005_rename_exprience_jobdata_experience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appdyjob',
            new_name='AppdlyJob',
        ),
    ]
