# Generated by Django 5.0.3 on 2024-03-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_rename_appdyjob_appdlyjob'),
        ('employer', '0005_rename_exprience_jobdata_experience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppdlyJob',
            new_name='ApplyJob',
        ),
    ]
