# Generated by Django 5.0.3 on 2024-03-24 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_remove_applyjob_cover_letter_remove_applyjob_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.expriance'),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.qualificationdata'),
        ),
    ]
