# Generated by Django 5.0.3 on 2024-03-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_applyjob_experience_applyjob_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='experience',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='candidate.expriance'),
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='qualification',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='qualification',
            field=models.ManyToManyField(blank=True, null=True, to='candidate.qualificationdata'),
        ),
    ]
