# Generated by Django 5.0.3 on 2024-03-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_remove_applyjob_experience_applyjob_experiences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='qualification',
            field=models.ManyToManyField(blank=True, to='candidate.qualificationdata'),
        ),
    ]
