# Generated by Django 5.0.3 on 2024-03-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_alter_applyjob_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='phone',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
