# Generated by Django 5.0.3 on 2024-03-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_applyjob_apply_date_alter_candidateprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlist', 'Shortlist'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
