# Generated by Django 5.0.3 on 2024-03-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_companydata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
