# Generated by Django 5.0.3 on 2024-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_jobdata_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdata',
            old_name='exprience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='jobdata',
            old_name='expairy_date',
            new_name='expiry_date',
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Temporary', 'Temporary'), ('Remote', 'Remote'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
