# Generated by Django 5.0.3 on 2024-03-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_rename_exprience_jobdata_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
