# Generated by Django 5.0.3 on 2024-03-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_jobdata_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobimage'),
        ),
    ]
