# Generated by Django 5.0.3 on 2024-03-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_jobdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='post_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
