# Generated by Django 5.0.3 on 2024-03-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_jobdata_post_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
