# Generated by Django 5.0.3 on 2024-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_alter_jobdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='experience',
            field=models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Less than 1 year', 'Less than 1 year'), ('1-3 years', '1-3 years'), ('3-5 years', '3-5 years'), ('5-10 years', '5-10 years'), ('More than 10 years', 'More than 10 years'), ('Any', 'Any')], default='Any', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Any', 'Any')], default='any', max_length=10, null=True),
        ),
    ]
