# Generated by Django 5.0.3 on 2024-03-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_alter_jobdata_experience_alter_jobdata_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='category',
            field=models.CharField(blank=True, choices=[('Accounting / Finance', 'Accounting / Finance'), ('Automotive Jobs', 'Automotive Jobs'), ('Customer', 'Customer'), ('Design', 'Design'), ('Development', 'Development'), ('Health and Care', 'Health and Care'), ('Human Resource', 'Human Resource'), ('Marketing', 'Marketing'), ('Project Management', 'Project Management')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Any', 'Any')], default='Any', max_length=10, null=True),
        ),
    ]
