# Generated by Django 5.0.3 on 2024-03-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_companydata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Paused')], default=True, null=True),
        ),
    ]
